### PR TITLE
Fix anchor link nesting

### PR DESCRIPTION
**Pull request by sergioc**
## Overview

This PR introduces following changes to the UI:
 * Row has no hover state any more. The name of the endpoint is always a link to monitoring details page and envelope icon is a link to failed messages group
 * The endpoint details page will show an empty state if there is no monitoring data available due to connectivity, configuration issues etc.

### All is fine
image

### Monitoring is not available
image

### Monitoring details empty state
image

### CODE REVIEW

**Comment by tmasternak** [comment]
@sergioc  @WilliamBZA the final changes are ready for review

**Comment by sergioc** [comment]
Approved (can't use GH built-in approval system since I opened the PR)

**Comment by WilliamBZA** [comment]
Is there a corresponding milestone with other features for this release?

**Comment by tmasternak** [comment]
@WilliamBZA milestone created.

**Pull request merged**
