### PR TITLE
Monitoring endpoint grouping

### PR DESCRIPTION
**Pull request by timbussmann**

### CODE REVIEW

**Review by sergioc — APPROVED** [review]

**Comment by JSCProjects** [comment]
Great functionality! Would also be nice if we also can group on "-". For viewing purposes tabs could also be an option!

**Comment by timbussmann** [comment]
@JSCProjects are you using both `.` and `-` in combination or just one or the other?

**Comment by JSCProjects** [comment]
We are using both, because we started using "-" and after a getting a Cogin Queue Explorer license we saw it was capable to group it when using "." then we started to use "." and "-" is legacy, but the grouping convention of naming endpoints is the same.

**Comment by timbussmann** [comment]
thanks for the detail. Supporting both in combination might be a bit tricky with the current implementation as it also does "reconstruct" the name be combining the splitted segments again, and in this case it would need to know a lot more to do that properly. Doing `.` or `,` alone would be easier to support. But I can forward this as a feature request for a further improvement 👍

**Pull request merged**
