### PR TITLE
Change to new json format

### PR DESCRIPTION
**Pull request by WilliamBZA**
Changes to the new json format

### CODE REVIEW

**Comment by timbussmann** [comment]
changes look good, can you include a sample of the new format on the issue description just to verify correctness?

**Comment by WilliamBZA** [comment]
Looks like so:

```json
[  
   {  
      "name":"TestEndpoint@williamb-pc",
      "data":{  
         "timestamps":[  
            "2017-07-05T11:03:36.7156633+02:00",
            "2017-07-05T11:03:37.7156633+02:00"
         ],
         "criticalTime":[  
            10,
            5
         ],
         "processingTime":[  
            15,
            16
         ]
      }
   }
]
```

**Comment by timbussmann** [comment]
you need to adjust the tests btw.

**Comment by WilliamBZA** [comment]
Should we introduce the average calculations as part of this?

**Comment by WojcikMike** [comment]
LGTM but need a rebase ;)

**Pull request merged**
