### PR TITLE
Hiding mobile navigation when the link is clicked

### PR DESCRIPTION
**Pull request by WojcikMike**
Fixes: #312

### CODE REVIEW

**Comment by WojcikMike** [comment]
@Particular/servicepulse-maintainers please review and merge. 
Current behaviour is that when the mobile menu is expanded clicking on any of the links on the menu will collapse it. 
There is an question should we actually expand the functionality to collapse the menu even when you click outside of the menu itself. I am gently leaning towards this as currently being on main screen one can click on "Failed Message" big button and the menu will stay expanded witch is a bit counter intuitive.

**Comment by WilliamBZA** [comment]
@WojcikMike I'm happy with the code, but should we not address the question you outlined before merging?

**Comment by WojcikMike** [comment]
After discussing with @WilliamBZA @kbaley the decision was made to hide the menu when user click outside of it. The code was changed accordingly and issue description as well

**Comment by sergioc** [comment]
:+1:

**Pull request merged**
