### PR TITLE
Endpoint filtering for monitoring view

### PR DESCRIPTION
**Pull request by timbussmann**
Adds a text input field that allows filtering endpoints by their name. In addition the filter can also be provided via search param in the URL so that filters can be shared and saved via bookmarks.

This is a draft PR, missing proper styling and more.

### CODE REVIEW

**Comment by timbussmann** [comment]
this seems to work fine in combination with the SC-connection embedded in the URL query string.

**Comment by timbussmann** [comment]
I moved the filter input to the same location as on the heartbeats view. I couldn't reuse the existing classes out of the box as they contains some specific magin settings and other stuff related to the position on the heartbeats view.

image

I can finish the styling next week, however I'm not 100% convinced about the location. Since this filters by endpoint name, does it make sense to have the filter input on the exact opposite side of the screen? This feels a bit counter-intuitve, thoughts @sergioc ?

**Comment by timbussmann** [comment]
tried to tweak the styling. This has been a CSS nightmare due to get the correct "right-alignment" of the time scale and the filter input due to to all the styles applied to the nav elements (used for the timerange selectors).

image


@sergioc please review and feel free to fix the CSS ;)

**Review by seanfarmar — APPROVED** [review]
LGTM

**Review by sergioc — APPROVED** [review]

**Pull request merged**
