### PR TITLE
Switch installer to use classic theme

### PR DESCRIPTION
**Pull request by gbiellem**
The "Black Surface" theme used in  the ServicePulse Installation is broken out of the box.  See #233 

This PR is to switch the theme to the classic theme with Particular specifiic logos

### CODE REVIEW

**Comment by gbiellem** [comment]
@petersgiles @sergioc 

Can you take a look at this and see if you are happy with it.  The resultant installer for this branch can be found here: - http://builds.particular.net/repository/download/ServicePulse_1NewBuil/137556:id/assets/Particular.ServicePulse-1.4.0.exe

**Comment by gbiellem** [comment]
@sergioc can you confim that the background on the SP_installer_initial.jpg is supposed to be a light grey.  The other ones you did are in the zip are white.

**Comment by sergioc** [comment]
> @sergioc can you confim that the background on the SP_installer_initial.jpg is supposed to be a light grey.

@gbiellem you're right, I fixed it and made the background white.

**Comment by sergioc** [comment]
Regarding the rest of the installer, I see 2 issues with the following screen:

2015-12-14 at 07 55

1) The Back button is disabled and I see no reason for it to be disabled.
2) The text "Instance URI" is cut off at the bottom

In addition to the above, I'm wondering about the doco that pops-up automatically after the installation. I don't think it's a good follow-up to installing SP. A general intro to SP would make more sense, I think. But since we don't have that, how about we show on the last screen a list with the following links (which together form the intro to the main features):

**Useful documentation articles to get started:**
- [Endpoints and Heartbeats in ServicePulse](http://docs.particular.net/servicepulse/intro-endpoints-heartbeats)
- [Failed Message Monitoring in ServicePulse](http://docs.particular.net/servicepulse/intro-failed-messages)
- [Custom Check Monitoring in ServicePulse](http://docs.particular.net/servicepulse/intro-endpoints-custom-checks)

**Comment by gbiellem** [comment]
Thanks @sergioc 

- Not sure why back is disabled - Will fix
- Don't see the text cut off on my machine, I'll adjust it and get you to retest.

The installer actually pops up http://www.particular.net/Installation-completed?installer=ServicePulse&version=[ProductVersion]   So the page you don't want displayed is not hard coded in the installer - it's a redirect from the main site.   I'm fine with adding links to the installer "installation complete" screen if we pull out the web popup but I assume that would also affect any stats collection we do on that page.   I'd also want to do this consistently on all the installers

**Comment by sergioc** [comment]
@gbiellem the reason I suggest the list of links is because the page that opened automatically for me from http://www.particular.net/Installation-completed?installer=ServicePulse&version=%5BProductVersion%5D was http://docs.particular.net/servicepulse/intro-endpoints-heartbeats

Is that the page that is supposed to open?

**Comment by gbiellem** [comment]
@sergioc AFAIK it's been that way since V1.   I think your original comment about there not being a general intro into SP is the the reason it goes there, it's the closest thing there is to an overview.

**Comment by sergioc** [comment]
@gbiellem I opened an issue requesting an SP intro doco: https://github.com/Particular/docs.particular.net/issues/976

**Comment by gbiellem** [comment]
@petersgiles @sergioc  - Take 2. Please review
The resultant installer for this branch can be found here: - http://builds.particular.net/repository/download/ServicePulse_1NewBuil/138049:id/assets/Particular.ServicePulse-1.4.0.exe

**Comment by sergioc** [comment]
Few more comments:

1) Product EULA mentions "NServiceBus license agreement" instead of Particular Software:

screenshot 2015-12-16 09 12 13

2) "Folder:" text shows below path

2015-12-16 at 09 13

3) I have no clue why it says "Advanced installer" at the bottom, it seems redundant. I'd remove that to prevent it from raising questions:

2015-12-16 at 09 13 1

**Comment by gbiellem** [comment]
@sergioc 

1.  All of the license agreements say "NServiceBus" these come from @SamCamhi so I assume there is a legal reason for this.  Remember we are NServiceBus Ltd. doing business as Particular Software.  

2.  Oops - will fix. Not sure why it's off since that's an OOTB screen I haven't updated.

3.  This is just some over zealous marketing in the advanced installer templates.  They've actually made it quite difficult to remove.  I checked the SC installer and it's present there as well.  I'll see how much effort it is to pull out but frankly i think it's fine to stay there as is.

**Comment by gbiellem** [comment]
Since the "Advanced Installer" watermark is part of the template and not the project I've had to hack every screen to remove it.  This works fine but it means it anyone adds a new screen they'll have to remember to do the same.

**Comment by gbiellem** [comment]
@sergioc  @petersgiles   Updated version - http://builds.particular.net/repository/download/ServicePulse_1NewBuil/138267:id/assets/Particular.ServicePulse-1.4.0.exe

I believe this is now good enough to merge.

**Comment by petersgiles** [comment]
I'm happy with it

**Comment by sergioc** [comment]
@gbiellem is it possible to remove the "modify" option from the installer, when SP is already installed? It doesn't make sense to have it there since there's no additional customization possible besides removing it:

screenshot 2015-12-17 10 47 56

The rest of the installer looks good. (I'll discuss the EULA issue with @SamCamhi separately)

**Comment by gbiellem** [comment]
@sergioc  - yes it is.  I'll tweak that in the morning

**Comment by gbiellem** [comment]
@sergioc @petersgiles  I removed the modify option 

 http://builds.particular.net/repository/download/ServicePulse_1NewBuil/138437:id/assets/Particular.ServicePulse-1.4.0.exe

**Comment by gbiellem** [comment]
Please review and merge if you have no other issues.

**Comment by sergioc** [comment]
@gbiellem a few questions:

1) Was your intention to remove all options to manage the installation or you tried to only remove the Modify option? I'm asking because when I choose to uninstall from Programs&Features, it immediately starts uninstalling after authorizing the UAC, there's no confirmation prompt (we either need that, or the other options screen without the modify option).

2) When the uninstallation completes, there's no confirmation that it successfully uninstalled. It'll just silently exit.

3) Sometimes after uninstalling it display this:

screenshot 2015-12-18 08 07 44

4) After SP uninstalls, it leaves behind its entry in the Programs&Features list.

**Comment by gbiellem** [comment]
@sergioc  

1.   No that's a bug. Will fix

2.  That's the default when uninstalled via add/remove programs but not when the original uninstall is used.  I have not found an acceptable way around that yet

3.  Can't do anything about that one. That's a built in Windows feature we have no control over

4.  It's a known issue with Add/Remove programs and not isolated to our installer. Refresh the screen with an F5 or close and open and you will see it's actually not there.

**Comment by gbiellem** [comment]
@sergioc I'll have to put this  on hold until we upgrade Advanced Installer. We're currently on 10.6 and have no maintenance. Some of the problems I'm hitting getting this working the way you want were addressed in 11.1.  I'll ping @SamCamhi  and see if we can update.

**Comment by sergioc** [comment]
@gbiellem :+1:

**Comment by SamCamhi** [comment]
@gbiellem updated maintenance.  Also, got a 6 month free trial for another product.  Sent you license key and info

**Comment by gbiellem** [comment]
Awesome @SamCamhi - thanks

**Comment by petersgiles** [comment]
@gbiellem can we merge this one now

**Comment by gbiellem** [comment]
Not yet. I parked this until the build agents were updated to V12 of Advanced Installer
That's done now so I guess I should finish it off.

**Pull request merged**
