### PR TITLE
Added releasing instructions

### PR DESCRIPTION
**Pull request by johnsimons**
Still need to add more screenshots.

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/servicepulse-maintainers thoughts so far ?
I will capture more screenshots for the Octopus steps.

**Comment by WilliamBZA** [comment]
Fantastic

:+1:

**Comment by johnsimons** [comment]
@Particular/servicepulse-maintainers this is now done

**Comment by WilliamBZA** [comment]
Thanks for the help!

**Pull request merged**
