### PR TITLE
 Failed messages to display UNKNOWN when data is missing instead of blank or min date

### PR DESCRIPTION
**Pull request by johnsimons**
When an NServiceBus endpoint receives messages from external systems such as BizTalk, TIBCO, etc. directly, the message itself will not contain regular NServiceBus headers. Without them ServiceControl cannot provide all usual information. For example, it won’t be able to determine when message was sent or what is its type.

To ensure that you are able to monitor your endpoints and have valuable metadata from ServiceControl, it becomes important as to how you integrate these messages. If for some reason failed messages will miss some metadata ServicePulse will handle it better by providing more meaningful defaults and descriptions.
Here is an example:
image

### CODE REVIEW

**Comment by johnsimons** [comment]
@weralabaj is the description ok ?

**Comment by weralabaj** [comment]
@johnsimons Yes, it's good. Are you going to email that to customers?

**Comment by weralabaj** [comment]
Few tiny changes:

When an NServiceBus endpoint receives messages from external systems such as BizTalk, TIBCO, etc. directly, the message itself will not contain regular NServiceBus headers. Without them ServiceControl cannot provide all usual information. For example, it won’t be able to determine when message was sent or what is its type. 

To ensure that you are able to monitor your endpoints and have valuable metadata from ServiceControl, it becomes important as to how you integrate these messages. If for some reason failed messages will miss some metadata ServicePulse will handle it better by providing more meaningful defaults and descriptions.
Here is an example:

**Comment by johnsimons** [comment]
> Are you going to email that to customers?

No, this is just for release notes

**Pull request merged**
