### PR TITLE
Remove the old yaml file

### PR DESCRIPTION
**Pull request by WojcikMike**

### CODE REVIEW

**Comment by bording** [comment]
Have you checked which versions of GitVersion are being used? You'd want to make sure everything is either on 3.6.5 if using the old project system, or 4.0.0-beta12 if using the new project system before removing this file.

Make sense to upgrade them as part of this PR if needed.

**Comment by WojcikMike** [comment]
@bording some ancient version 2.0.1 was used, I've updated it to 3.6.5. Please have a look

**Comment by WojcikMike** [comment]
The build failed :( I will review it tomorrow morning.

**Comment by bording** [comment]
Everything seems to build locally fine, so I'm not quite sure why the build failed.

However, looking at the repo, I think it needs some love and cleanup in general, so maybe it would make sense to convert everything over to the new project system and get it all nice and working? I can do that if it makes sense.

**Comment by WojcikMike** [comment]
Yep @bording go for it.

**Comment by bording** [comment]
FYI, I have started on it, should have a PR ready tomorrow.

**Comment by bording** [comment]
New PR: #742

**Pull request closed without merging**
