### PR TITLE
Add Endpoint Details page

### PR DESCRIPTION
**Pull request by WilliamBZA**
Dependent on : https://github.com/Particular/ServicePulse/pull/473

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Ready for review, but still dependent on #473

**Comment by WilliamBZA** [comment]
Rebased, should be ready for merge

**Comment by WojcikMike** [comment]
We need to add here refreshing the data, before merging

**Comment by SimonCropp** [comment]
can this branch be deleted?

**Comment by WilliamBZA** [comment]
Correct, it can. Must have been an oversight.

**Pull request merged**
