### PR TITLE
Add package manager to web libraries

### PR DESCRIPTION
**Pull request by WojcikMike**
Connects to: #370 

For now I used exactly the same versions of libraries, and pushed them to git, so that we don't need to do any change on builder yet.

The end goal would be to install on team city nodejs and bower and download dependencies before build.

ATM I create: lib-manual to hold a library which I couldn't find on bower:
page-width-functions - I am not sure where it comes from. 

cc: @Particular/servicepulse-maintainers please have a look.

### CODE REVIEW

**Comment by kbaley** [comment]
Do we need all the packages in app/lib to be in source control? My memory of bower is fuzzy but I thought the idea was we could use it to get them so we wouldn't need them in source.

**Comment by WojcikMike** [comment]
> Do we need all the packages in app/lib to be in source control? My memory of bower is fuzzy but I thought the idea was we could use it to get them so we wouldn't need them in source.

Your memory serves you well my young padawan. I did it for now, so that Team City doesn't need bower installed. After we coordinate the effort of installing bower on build agents we will be able to exclude the folder from git.

**Comment by WojcikMike** [comment]
For now I will pause work on this as it was a bit hasty to pull bower in. First we want to make decision where we want to take ServicePulse technically and adjust used frameworks to that vision.

**Comment by WilliamBZA** [comment]
I would rather configure Bower on TC than include the packages in the Repo. Once they're in git, they're in forever.

**Comment by WojcikMike** [comment]
Closing for now as it needs to be discussed in more details

**Pull request closed without merging**
