### PR TITLE
Moving the dependecies to npm

### PR DESCRIPTION
**Pull request by WojcikMike**
I only moved the dependencies, the things still needed to do:
 - remove wiredep and bower from references and build scripts
 - bundle dependencies into a webpack module and put it in the app folder
 - update the references to not use exact versions of dependencies

### CODE REVIEW

**Comment by WojcikMike** [comment]
The removing of the bower is done. Now I need to rebase

**Comment by WojcikMike** [comment]
And rebased. @WilliamBZA @sergioc can you please not only review the code, but also go through the screens and see if everything looks ok?

**Comment by WojcikMike** [comment]
Tests are fixed

**Comment by WojcikMike** [comment]
@WojcikMike it seems that the styles are off, for headers and tabs Please have a look

**Comment by WojcikMike** [comment]
Ok I fixed the configuration so now there is 1 css created called vendor.css that contains all referenced css files. It seems to be working now.

**Comment by sergioc** [comment]
Looks alright, but I'm not sure if it's a good idea to merge before we do #580 and #583

**Comment by WilliamBZA** [comment]
Rebased, renamed `recoverability` to shell.

**Pull request merged**
