### PR TITLE
Added Get new version! directive to dashboard

### PR DESCRIPTION
**Pull request by petersgiles**
added "Get new version!" notification
that looks like Team city footer on ServicePulse Dashboard

### CODE REVIEW

**Comment by gbiellem** [comment]
@weralabaj  Do you want to review this since you're plying in the SP space?

**Comment by gbiellem** [comment]
This would address #22 and #23

**Comment by weralabaj** [comment]
@TheBaconPhoenix @gbiellem Should we also take into account the fact that new SP version needs to be compatible with the particular SC version to work? We have exactly that concern in [FeatureDev #272](https://github.com/Particular/FeatureDevelopment/issues/272). In that case the new SP functionality requires SC upgrade too.

Imho the simplest solution would be to upgrade all tools (SC, SP, SI) at once, not only SP. Any concerns regarding that?

**Comment by weralabaj** [comment]
@TheBaconPhoenix Added a few comments, mostly questions.

**Comment by gbiellem** [comment]
> Should we also take into account the fact that new SP version needs to be compatible with the particular SC version to work?

:+1: Makes sense to re-use if you're working on feature switching stuff in SP

> Imho the simplest solution would be to upgrade all tools (SC, SP, SI) at once, not only SP. Any concerns regarding that?

I'm assuming because feature switching is a pain :)

**Comment by weralabaj** [comment]
@gbiellem 
> :+1: Makes sense to re-use if you're working on feature switching stuff in SP
Not really, we have hardcoded the version number that supports what we need :( "Advanced versioning" afair is supposed to be more like "is this feature supported in the sc version I currently have" rather than forcing SP to know what SC version it needs. But that was out of scope for 272.

**Comment by TheBaconPhoenix** [comment]
@weralabaj @gbiellem 

> I'm not sure what 'M' stands for in restrict?
> I think we don't need 'A', as it's used only as an element.
> I'm not an Angular ninja so just a question really - why should that part be a separate directive? Seems 
>  that now we have directives only for heavily reused elements such as time display, that doesn't seem 
>  like a re-usable component.

M restrictions allow you to write your directive like so  
Here is a good reference  http://www.angularjshub.com/examples/customdirectives/restrict/
Just habit on my part I guess as I didn't want to be prescriptive about we use it. We can talk about how we want to reuse directives and settle on one. :smiley:

semverUtils is a library that @johnsimons sent me that I hacked a bit to get it to work. I think you're right about some of the logic you mentioned being superfluous and I think I can rewrite it as a generic service that suits our needs specifically. Including the notion 'is newer' vs 'is different'.

**Comment by petersgiles** [comment]
@weralabaj are you happy with my latest revisions? Merge?

**Comment by weralabaj** [comment]
@petergiles I'd only move the feature from directives directory into a "feature" directory, similar to what is done for failedMessages. Looks ok for me.

**Pull request merged**
