### PR TITLE
[WIP]: 1.4.0 release

### PR DESCRIPTION
**Pull request by petersgiles**
ServicePulse - release 1.4.0

#### Fixed bugs

- [Global modal for when comms go out](https://github.com/Particular/ServicePulse/issues/191) - signlr comms goes through global service now
- [at 1400+ pixels the menu text is not visible](https://github.com/Particular/ServicePulse/issues/225) - redesigned layout for reactive small screen 
- [https://github.com/Particular/ServicePulse/issues/251 ](https://github.com/Particular/ServicePulse/issues/251)
- [Notifications should not result layout changes ](https://github.com/Particular/ServicePulse/issues/284)
- [Lost connection to SC - when browser idle over night ](https://github.com/Particular/ServicePulse/issues/282) - Notification improvements
- [Improve failed messages navigation from activated group state](https://github.com/Particular/ServicePulse/issues/253)  - removed tabbed interface, improved navigation 
- ["Well done, no errors here" state shows while loading SC data](https://github.com/Particular/ServicePulse/issues/258)  - removed message during loading, improved navigation
- [Pressing the ServicePulse logo in the top left does not show the dashboard](https://github.com/Particular/ServicePulse/issues/269)  - pressing the logo returns the user to the dashboard
- [First text column on dashboard should be truncated for long values](https://github.com/Particular/ServicePulse/issues/272)  - added overflow and ellipses 
- [Retry icon is confusing, looks like refresh](https://github.com/Particular/ServicePulse/issues/273)  - removed icons in favor of text
- [Row information on dashboard is really confusing](https://github.com/Particular/ServicePulse/issues/274)  - redesigned row boxes for better clarity 
- [Add badges to menu with totals](https://github.com/Particular/ServicePulse/issues/277)  - added badges to the menus with totals
- [Menu should be visible when scrolling down on large screen](https://github.com/Particular/ServicePulse/issues/278)  - fixed the menu at the top of the screen
- [Repeated failure count should be presented immediately, not in a tooltip](https://github.com/Particular/ServicePulse/issues/279)  - put the amount of repeated failures in the tag
- [On Failed Messages Screen Message headers don't wrap](https://github.com/Particular/ServicePulse/issues/281)  - corrected wrapping of `pre` tags
- [Selected message not selected after returning to messages tab](https://github.com/Particular/ServicePulse/issues/262) is not relevant anymore as the tabbed interface has been removed
- [Number alignment in the failed message grouping list](https://github.com/Particular/ServicePulse/issues/263) is improved through different design
- [Row info layout on grouping improvements](https://github.com/Particular/ServicePulse/issues/275) - redesigned row boxes for better clarity how we choose the name of the group hasn't been addressed

#### Are you affected?

All users that are using ServicePulse are affected.

#### Should you upgrade immediately?

It is recommended that all users uprade to the latest version of ServicePulse for a superior user experience

Regards,

Particular Software

### CODE REVIEW

**Comment by johnsimons** [comment]
@petersgiles it would be nice to start writing the release notes for this, this way we know what all the improvments are.
So how do we sell this ?

**Comment by petersgiles** [comment]
yes, I'm just consolidation all the bug fixes in the description, will go through a bunch of the value proposition with @sergioc tomorrow. 

If you have any insight about the communication I would welcome it. There's a lot of good stuff in this release. I want thorough testing and good doco to go with it.

**Comment by petersgiles** [comment]
ServicePulse is the easy way to monitor your distributed system
ServicePulse tells you when messages fail
ServicePulse lets you retry individual messages or groups of messages on all supported transports

For Decision makers who need to know that their systems will survive failure ServicePulse is the tool that gives their staff insight into distributed system message processing

For Change Managers who need to know what is currently active in an environment ServicePulse catalogs message endpoints and shows if they are active or not

For Operations personnel who need to know when something is failing ServicePulse is a browser based monitoring tool that presents enough information for them to triage a problem

For Developers who provide 3rd level system support ServicePulse is the first place to go to to understand messaging behaviors in complex production environments  

There has been a lot of feedback in the last few weeks and we have taken an holistic approach to solving the problems you have been facing with ServicePulse. 
- We have improved the navigation so that you can see where you are whatever you're doing in ServicePulse. 
- We have cleaned up the presentation of information to reduce confusion and distracting information.
- We have made improvements to the Failed Messages screen to enhance your experience which you are managing a production issue. Everything you are used to is still there, it's just presented better.
- We have tried to make the experience around retrying groups better. At the moment it is very difficult to state categorically how the processing of a group went. The improvements we have made will give you a better idea of how a group was processed,

**Comment by adamralph** [comment]
Why is a release being performed by a merge from `notifications-toaster` to develop? Shouldn't the feature already been on develop, and the release performed via a merge from `develop` to `master`?

**Comment by petersgiles** [comment]
You are right...this should be in develop. Will talk to contributors and merge it.

**Comment by johnsimons** [comment]
@petersgiles I actually really like the way you have done this in a PR and once ready to release (and only then), you merge it.
This is the way we work in ServiceControl, we don't have `develop` branch, maybe something this repo should also consider, since there is no need for it.
Ping me if you need me to help you get started with it ?

**Comment by petersgiles** [comment]
@johnsimons yes I like the way ServiceControl it doing it. To me its a better model for collaboration and gives better oversight of the goals of a particular development effort. 

I think we will formalise this approach for SP once this is released

**Comment by petersgiles** [comment]
2016-02-25 at 11 51
2016-02-25 at 11 55
2016-02-25 at 12 01

UI issues remaining need doing

**Comment by johnsimons** [comment]
@petersgiles 
image

Should those be blue and orange ?

**Comment by johnsimons** [comment]
image

There was an issue of confusing these kind of tags as clickable buttons, is there a way to style them so it does not give that impression ?

**Comment by petersgiles** [comment]
@johnsimons good points we will try and address them soon

**Comment by sergioc** [comment]
screenshot 2016-02-25 20 25 11

This should be info, not warning.

**Comment by sergioc** [comment]
@petersgiles what's left to do:

- show crumble bar and hide tabs when inside a message group
- proper empty states
    - use same presentation we had before
    - fix loading custom checks screen or configuration, which start with a "no data" state
- fix mobile screens for Configuration screen
- show count badge to mobile menu icon of nav items have a count badge
- Change reconnected toast class to `info`
- Improve text on confirmation dialogs
- Kill endpoints overview screen and rename "Configuration" screen title and nav link to Endpoints
- show loading state in failed messages screen under tabs

**Comment by sergioc** [comment]
@petersgiles and:

- change page `<title>` to following format: `{{Current screen name}} • ServicePulse`. Bonus when user's attention is required :-) : `({{total no. of problems}}) {{Current screen name}} • ServicePulse`

**Comment by mat-mcloughlin** [comment]
The design on this is really good guys.

**Comment by mat-mcloughlin** [comment]
I've had a run through as much of this as I can today. I've come across a couple of possible issues. Not sure which are important so feel free to ignore any of them:

- [ ] Failed Messages don't populate in real time like it does on the dashboard. However is this by design so they don't move all over the place?

- [ ] The tabs on the failed message page have the wrong hover over cursor (It's not a hand)
image

- [ ] When you try and archive the final failed message group it does perform the action but the UI never updates
image

- [ ] This sort of relates to https://github.com/Particular/ServicePulse/issues/279 but when you retry a message it doesn't update the retry count without refreshing the page

- [ ] https://github.com/Particular/ServicePulse/issues/279 The service pulse logo still doesn't take you to the dashboard

**Comment by petersgiles** [comment]
These 2 need SC to be fixed

> Failed Messages don't populate in real time like it does on the dashboard. However is this by design so they don't move all over the place?

Yes the amount of jiggling that this could create on the screen would be horrendous...users might click the wrong button if the list items are updating all the time

    This sort of relates to #279 but when you retry a message it doesn't update the retry count without refreshing the page

Same as above...we do hope to improve though as SC improves

**Pull request merged**
