### PR TITLE
Removing duplicated AVG in Processing Time 

### PR DESCRIPTION
**Pull request by tmasternak**
## Overview
Removing duplicated AVG in the processing time value on endpoint details screen.

### CODE REVIEW

**Comment by WojcikMike** [comment]
Is it WIP?

**Comment by tmasternak** [comment]
@WojcikMike not anymore ;)

**Comment by WilliamBZA** [comment]
What's happening with this PR?

**Comment by sergioc** [comment]
It's ready to merge. As previously discussed, another maintainer should do that or approve.

**Pull request merged**
