### PR TITLE
Development time convenience

### PR DESCRIPTION
**Pull request by mikeminutillo**
Adds a cmd file to run the 3 parts of the system needed for development:

- Vue dev server
- Angular dev server
- nginx proxy

I had to go to the readme every day to start up everything but that can be automated :)

### CODE REVIEW

**Review by johnsimons — CHANGES_REQUESTED** [review]
It doesn't work on Mac 😜

**Comment by mikeminutillo** [comment]
> It doesn't work on Mac 😜

Write a bash script to do the same thing ;)

**Comment by PhilBastian** [comment]
given that this is a windows specific script, could it also check for the docker process and start it if it isn't already?

**Review by johnsimons — APPROVED** [review]
I let it go for now 😉

**Review by PhilBastian — APPROVED** [review]

**Pull request merged**
