### PR TITLE
Add http server

### PR DESCRIPTION
**Pull request by WilliamBZA**
Adds http`server dev-dependency so that users can develop without Visual Studio

@mauroservienti this is what I was talking about

### CODE REVIEW

**Comment by mauroservienti** [comment]
perfect, thanks!

**Comment by WilliamBZA** [comment]
@sergioc I meant to do this PR ages ago. It means you no longer have to spin up a windows VM to work on SP.

**Comment by mauroservienti** [comment]
Can this be merged straight away then?

**Comment by WilliamBZA** [comment]
Just waiting for pulse maintainers review 😄

**Comment by WojcikMike** [comment]
reviewed, if it matters

**Pull request merged**
