### PR TITLE
Added sort options and corrected bug with direction

### PR DESCRIPTION
**Pull request by petersgiles**
fixes: https://github.com/Particular/ServicePulse/issues/245

### CODE REVIEW

**Comment by petersgiles** [comment]
@johnsimons please review and merge

**Comment by petersgiles** [comment]
@johnsimons have spoken with @sergioc and the sort works as he would like and works with the load more functionality please review and merge

**Comment by johnsimons** [comment]
@petersgiles this looks good IMO.

The only thing is, should we update the description of the PR to include better description of this feature and maybe also a screenshot. This way the release notes are done

**Comment by petersgiles** [comment]
fixes https://github.com/Particular/ServicePulse/issues/245

**Pull request merged**
