### PR TITLE
Create a Retention policy screens for retention policy changes in ServiceControl

### PR DESCRIPTION
**Pull request by johnsimons**
task-force: @petersgiles @johnsimons @sergioc @boblangley 

//cc @Particular/servicepulse-maintainers @mat-mcloughlin @WilliamBZA 

Component of https://github.com/Particular/PlatformDevelopment/issues/667
Related to https://github.com/Particular/ServiceControl/issues/691

related to: https://github.com/Particular/ServicePulse/issues/241

## Plan of Attack

- [x] A new screen for archive
- [x] display a count of archived messages

failed-groups-tab

- [x] review individual archived messages

archived-messages

- [x] unarchive (when messages are unarchived the retry retention countdown resets

archived-messages-select-to-unarchive

- [x] sorting & filtering

archived-messages-time-groups

- [x] ServiceControl version incompatibility screen that will stop ServicePulse from working with lower/incompatible versions 

to test go to factory.shareddata and change the minimum version
version_incompatibility

You'll get redirected to an about screen with some information on it the top nav will hide and toasts will pop too

incompatible

- [x] Changes to documentation

Connects to https://github.com/Particular/PlatformDevelopment/issues/667

### CODE REVIEW

**Comment by sergioc** [comment]
@petersgiles Since the About screen isn't accessible anywhere normally, I changed it to focus on incompatibility warning notice.

**Comment by sergioc** [comment]
@petersgiles to-do from from today's sync:

- check width of archived messages list
- adjust dropdown filter button text to better indicate active state
- Do not show “Scheduled for deletion immediately” messages and subtract those from total counts

Notes from testing with @mauroservienti:

- Failed groups count doesn’t update if you unarchive a message from a group that had no failed messages before
- Should we add a help tooltip icon next to “Scheduled for deleting” with more info about what it means and how to configure the deletion policy?

**Comment by petersgiles** [comment]
> Since the About screen isn't accessible anywhere normally, I changed it to focus on incompatibility warning notice.

I was thinking that one day it will grow to include current configuration of everything so that devops know what they are dealing with without having to hunt around for stuff. but that's cool for now.

**Comment by petersgiles** [comment]
> Do not show “Scheduled for deletion immediately” messages and subtract those from total counts

The list management that this requires is a little tricky. I will attempt this as a nice to have after all the doco etc is done.

> Failed groups count doesn’t update if you unarchive a message from a group that had no failed messages before

fixed (the counts will update on a 5 sec timer as I have to poll for accurate data here)

**Comment by boblangley** [comment]
Ran ServicePulse from this branch with ServiceControl delete_errors branch. Everything related to failed messages works as expected, I just have not yet been unable to confirm the archive date filtering since I do not have any messages that old.

Found issues with unarchive button tooltip and the unarchive confirm dialog, they appear to share the message with the archive button / confirm. I am working on a commit to adjust these.

**Comment by petersgiles** [comment]
just storing these here for history

## original mockups

new mockup 1_2

new mockup 1

**Comment by sergioc** [comment]
> Found issues with unarchive button tooltip

Buttons with text labels should not require tooltips, that adds unnecessary redundancy. An issue was recently closed to address this, but it seems there's some leftovers, so I cleaned that up.

**Comment by sergioc** [comment]
@petersgiles during testing with @ramonsmits:

- we missed the option to unarchive all messages. Should that be made possible in this release or is there a reason you didn't include it?
- the notation for failure timestamp for archived messages is not consistent with that in the "all failed messages" tab
- there's no option to immediately delete a (selected) archived message. Why?

**Comment by petersgiles** [comment]
@sergioc @ramonsmits 

> we missed the option to unarchive all messages. Should that be made possible in this release or is there a reason you didn't include it?

I don't think we can do that in any meaningful way until grouped messages are implemented in servicecontrol

> there's no option to immediately delete a (selected) archived message. Why?

That would require an extension to the api that is outside the scope of this fix. Users can use the SC management tool to reduce the time to keep down to a minimum value. We were afraid if gave the option to select all and then a delete immediately function that users would risk putting too much load on the system. we can review and refine later.

**Comment by sergioc** [comment]
>> we missed the option to unarchive all messages. Should that be made possible in this release or is there a reason you didn't include it?

> I don't think we can do that in any meaningful way until grouped messages are implemented in servicecontrol Particular/PlatformDevelopment#635

What does this have to do with grouping?

**Comment by petersgiles** [comment]
Ok what is the 'ALL' I am meant to select? 

- Is it something that is time bracketed?
- Is it what is currently displayed?
- Is it everything in the current filter?
- Is it actually everything?
- Is it the exception group of the currently selected message?

The current API doesn't support these scenarios easily. From the client I can take a solid guess at some of them but I don't always have full information. I want to avoid querying everything in a data store that potentially has 1,000,000+ records just to determine if I can delete some of them or not.

**Comment by sergioc** [comment]
"All" means whatever can be showed on this screen (may not yet be displayed, but will be if you scroll to load more), based on the filtered time period you selected.

> I want to avoid querying everything in a data store that potentially has 1,000,000+ records just to determine if I can delete some of them or not.

We're referring to the ability to *unarchive* all, not delete.

**Pull request merged**
