### PR TITLE
Revised style of counts for failed msg tabs

### PR DESCRIPTION
**Pull request by sergioc**
Connects to #387

### CODE REVIEW

**Comment by sergioc** [comment]
@WojcikMike given the incongruity between counts for each failed group type, the count next to the "Failed groups" tab should be `!` whenever there's at least 1 failed group. Can you help with showing that instead of a number?

**Comment by WojcikMike** [comment]
@sergioc have a look. I made the ! to be dependent on a number of error messages. As if there are any messages than certain group classification can return a different number. Let me know what you think.

**Comment by sergioc** [comment]
Looks good. I didn't understand your comment fully. To confirm, it will always use `!`, right?

I'm also wondering whether we could indicate the no. of groups next to the name of each failed message group type in the dropdown. Like so:

2017-05-30 at 16 42


This would make it easier to correlate the group type counts with the `!`.

**Comment by WojcikMike** [comment]
@Particular/servicecontrol-maintainers for this UI change to be made an api to get group counts would have to be created (ideally one that takes classification). Without it, it would be hard to implement this

**Comment by sergioc** [comment]
Then let's split group type counts into a separate issue

**Comment by sergioc** [comment]
OK, new issue created: https://github.com/Particular/ServicePulse/issues/454

@Particular/servicecontrol-maintainers please review and merge this one.

**Pull request merged**
