### PR TITLE
Refactor uri service

### PR DESCRIPTION
**Pull request by colin-higgins**
Connects to https://github.com/Particular/ServicePulse/issues/326

Refactor uri service to handle leading slashes.
Remove sample tests that fail.

### CODE REVIEW

**Comment by johnsimons** [comment]
@colin-higgins does this still need to be merged ?

**Comment by colin-higgins** [comment]
I think it's still a good PR for cleaning some stuff up. Thoughts @petersgiles ?

**Comment by petersgiles** [comment]
yes I agree that the unused sample tests need to be dropped

**Comment by colin-higgins** [comment]
Added a test for the leading slash trimming and rebased

**Pull request merged**
