### PR TITLE
[WIP] Allow configuring SP connectivity via the web app

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
rebased on `master`

**Comment by mauroservienti** [comment]
Was observing a very strange behavior, like if the app was using a ghost `scConfig` in some places and the new `connectionsManager` in other places. Found a file that should not be there. Removed it in https://github.com/Particular/ServicePulse/pull/725/commits/88ec9003d66a3decd72f889151be27840222abe5 as webpack is recreating that `.dist.js` file in another dist directory.

Given that default URLs are not anymore set at installation time, the `app.constants.js` doesn't need to contain the `defaultConfig` object. Moved it to `connectionsManager` to simplify retrieval of default configuration when Pulse starts for the very first time.

**Comment by mauroservienti** [comment]
To be checked:

> Given that default URLs are not anymore set at installation time, the `app.constants.js` doesn't need to contain the `defaultConfig` object. Moved it to `connectionsManager` to simplify retrieval of default configuration when Pulse starts for the very first time (https://github.com/Particular/ServicePulse/pull/725/commits/2eb1e342f04c8be895c1dec7dbc198556fa32c08).

There are installer custom actions that deal with those values at install time, I'm not sure if moving them breaks the installation experience.

**Comment by WilliamBZA** [comment]
:+1: for the code. Boy scout rule followed for all the places where old code was touched and the new code doesn't introduce deeper coupling to angular.

**Comment by mauroservienti** [comment]
Closing in an attempt to resurrect TC, will open a new PR.

**Pull request closed without merging**
