### PR TITLE
Add command line validation

### PR DESCRIPTION
**Pull request by gbiellem**
related to #228

### CODE REVIEW

**Comment by gbiellem** [comment]
@petersgiles I think this is ready for review

**Comment by petersgiles** [comment]
So you had to override OptionSet to do Caseless stuff. Nice work. The tests seem to cover everything I can think of. Its so nice to have unit tests in ServicePulse

**Comment by gbiellem** [comment]
> So you had to override OptionSet to do Caseless stuff.

I did consider modifying optionset directly but this way it should be more upgrade friendly.

**Comment by petersgiles** [comment]
Yes, I preferred what you did.

**Pull request merged**
