### PR TITLE
If ServiceControl Api Uri is configured with or without a trailing slash the application will now behave properly

### PR DESCRIPTION
**Pull request by petersgiles**
relates to https://github.com/Particular/ServicePulse/issues/200

If there is a trailing slash on the end of the ServiceControl api uri in the config file ServicePulse would compensate for it inappropriately. Now if the config has a trailing slash or not ServicePulse will be able to handle it.

### CODE REVIEW

**Comment by petersgiles** [comment]
@johnsimons @colin-higgins please review

**Comment by johnsimons** [comment]
@petersgiles at first it scared me the ammount of code changed to fix a missing backspash.
But I think i see the approach u took and cover all the basis.
So :+1: to merge

Just for future, is there a way to test this ?

**Comment by petersgiles** [comment]
@johnsimons we need to look at a test framework perhaps karma but I've never run one up in anything other than gulp. Dunno how it would all work with team city etc.

**Comment by colin-higgins** [comment]
@petersgiles @johnsimons 

I've set up javascript tests in TeamCity before, I can get that up for us soon. We'd use a headless browser like PhantomJS to run the tests. PhantomJS is just an executable that you feed some arguments too, easy to add as a step in TeamCity.

**Pull request merged**
