### PR TITLE
[WIP]: toastr notifications

### PR DESCRIPTION
**Pull request by petersgiles**
Started to replace notifications with toasts. This helps with bugs around the interface moving when a notification is presented.

related to: https://github.com/Particular/ServicePulse/issues/251

### CODE REVIEW

**Comment by petersgiles** [comment]
@sergioc this has the toast pop up in it now, it's still a little 'noisy' we shall have to aggregate some of the notifications I think.

**Comment by sergioc** [comment]
Toast message types:

**Error type:**
- ServiceControl connection lost (warning)
- *other types of SC errors*

**Success:**
- **Group retry successful** N messages from group XXX successfully retried 
- **Group archive successful** N messages from group XXX successfully archived

**Warning**
- N messages failed (this toast wouldn’t be repeated, but the number inside the toast would simply update)
- **Group retry failed** N messages from group XXX failed to retry
- **Group retry failed** N messages from group XXX failed to archive

**Additional requirements:**
- Assuming we can easily aggregate the "N messages failed” toast, then all messages should be sticky and require the user to manually dismiss.
- Clicking on toast related to failed messages dismisses it and takes user to failed messages screen, “Messages group” showing
- Nice to have: a version in the singular for messages with counts.

**Comment by johnsimons** [comment]
Instead of fly in toasts (which can become quite distracting), should we consider the approach that Azure portal uses (the static panel at the bottom) ?

**Comment by sergioc** [comment]
@johnsimons Azure screenshot?

**Pull request closed without merging**
