### PR TITLE
Truncating endpoint names

### LINKED ISSUE #612: Long MessageTypes break UI
On the monitoring endpoint details screen, when the message type is long enough it will expand over it's row. It is a subset of issue reported in here: #581 

Example can be seen here:
image

On the wide screen the issue `almost` don't exist
image

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 1.12

### PR DESCRIPTION
**Pull request by HEskandari**
Resolves #612

### CODE REVIEW

**Comment by sergioc** [comment]
Seems like status icons are not following the endpoint text anymore, there's now a gap:

image

And truncating doesn't seem to work on Chrome v66.0.3359.139:

image

**Comment by HEskandari** [comment]
@sergioc which screens are these? I have only changed the monitoring list and details pages.

**Comment by HEskandari** [comment]
@sergioc well, this is what I see:

image

**Comment by HEskandari** [comment]
@sergioc BTW your screenshot above is from MessageTypes. What this PR address is the truncation of endpoint name.

**Comment by sergioc** [comment]
#612 is mostly about message type names and was expanded to include endpoint names. This PR will only partially resolve that issue.

I still cannot verify the fix here. Endpoints screen:

image

**Comment by WojcikMike** [comment]
@sergioc I think we need to break this problem into 2. first is to long endpoint names that we can solve with truncation of text as @HEskandari implemented. Second problem is what the issue is about that message types are to long. Example of such message type is:
Shared2.EventMessage, Shared2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;IMyEvent, Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

If we would apply trimming to this string we would get:
`... Culture=neutral, PublicKeyToken=null` for all of the rows

I think we should change how we display the data, and in the lable put only type of the message so:
Shared2.EventMessage (which in itself might be very long string). And show the remainging part in some sort of tooltip, or expandable space below the row. Either way something more than simply truncating the text.

**Comment by sergioc** [comment]
we already split properties into a separate row of text. I'd expect this issue to address only the truncating of message type names, so that it solves #612. Using your example:

> **Shared2.EventMessage**
> Shared2 Version=1.0.0.0 Culture=neutral PublicKeyToken=null IMyEvent Shared Version=0.0.0.0 Culture=neutral PublicKeyToken=null

Correctly parsing those properties into the second row could indeed be a separate issue and solve #581

**Comment by WojcikMike** [comment]
Were are we doing that? On 1.13 it looks like this:
image

**Comment by sergioc** [comment]
Seems like a bug. Here's how it renders message types from the monitoring demo:

image

**Comment by WojcikMike** [comment]
Please check how it looks in SP 1.13.1. Maybe this never got to the SP release, and clear the cache ;)

**Comment by WilliamBZA** [comment]
Closing this as we are not in agreement on how to resolve. It can be reopened too.

**Pull request closed without merging**
